CREATE TABLE "auth_user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(150) UNIQUE NOT NULL,
  "email" varchar(254) UNIQUE NOT NULL,
  "password" varchar(128) NOT NULL,
  "gdpr_consent" boolean DEFAULT false,
  "oauth_id" varchar(255),
  "twofa_secret" varchar(32),
  "twofa_enabled" boolean DEFAULT false,
  "is_active" boolean DEFAULT true,
  "is_staff" boolean DEFAULT false,
  "is_superuser" boolean DEFAULT false,
  "date_joined" timestamp DEFAULT (now()),
  "last_login" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "token_blacklist" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "token" text NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "expires_at" timestamp NOT NULL
);

CREATE TABLE "password_reset_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "token" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL,
  "used" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_profiles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "phone" varchar(20),
  "address" varchar(255),
  "city" varchar(100),
  "state" varchar(100),
  "postal_code" varchar(20),
  "country" varchar(2) DEFAULT 'FI',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "brands" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "price" decimal(10,2) NOT NULL,
  "stock_quantity" integer NOT NULL DEFAULT 0,
  "category_id" integer NOT NULL,
  "brand_id" integer,
  "images" json,
  "weight_kg" decimal(8,2),
  "dimensions" json,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "carts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "session_id" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "expires_at" timestamp
);

CREATE TABLE "cart_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "guest_email" text,
  "phone" text,
  "status" varchar(20) DEFAULT 'pending',
  "total_amount" decimal(10,2) NOT NULL,
  "billing_address" json NOT NULL,
  "shipping_address" json NOT NULL,
  "tracking_number" varchar(100),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "quantity" integer NOT NULL,
  "price_at_time" decimal(10,2) NOT NULL
);

CREATE TABLE "payments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "status" varchar(20) DEFAULT 'pending',
  "payment_method" varchar(50),
  "transaction_id" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "processed_at" timestamp
);

CREATE TABLE "reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "rating" integer NOT NULL,
  "review_text" text,
  "helpful_count" integer DEFAULT 0,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "review_helpful" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "review_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "action" varchar(100) NOT NULL,
  "resource_type" varchar(50),
  "resource_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX "idx_user_email" ON "auth_user" ("email");

CREATE INDEX "idx_user_username" ON "auth_user" ("username");

CREATE INDEX "idx_user_oauth_id" ON "auth_user" ("oauth_id");

CREATE INDEX "idx_product_name" ON "products" ("name");

CREATE INDEX "idx_product_price" ON "products" ("price");

CREATE INDEX "idx_product_stock" ON "products" ("stock_quantity");

CREATE INDEX "idx_product_active" ON "products" ("is_active");

CREATE INDEX "idx_product_created" ON "products" ("created_at");

CREATE INDEX "idx_product_category" ON "products" ("category_id");

CREATE INDEX "idx_product_brand" ON "products" ("brand_id");

CREATE UNIQUE INDEX "idx_cart_user" ON "carts" ("user_id");

CREATE INDEX "idx_cart_session" ON "carts" ("session_id");

CREATE INDEX "idx_cart_expires" ON "carts" ("expires_at");

CREATE UNIQUE INDEX "idx_cart_items_unique" ON "cart_items" ("cart_id", "product_id");

CREATE INDEX "idx_cart_items_cart" ON "cart_items" ("cart_id");

CREATE INDEX "idx_cart_items_product" ON "cart_items" ("product_id");

CREATE INDEX "idx_order_user" ON "orders" ("user_id");

CREATE INDEX "idx_order_guest_email" ON "orders" ("guest_email");

CREATE INDEX "idx_order_status" ON "orders" ("status");

CREATE INDEX "idx_order_created" ON "orders" ("created_at");

CREATE INDEX "idx_order_tracking" ON "orders" ("tracking_number");

CREATE INDEX "idx_order_items_order" ON "order_items" ("order_id");

CREATE INDEX "idx_order_items_product" ON "order_items" ("product_id");

CREATE INDEX "idx_payment_order" ON "payments" ("order_id");

CREATE INDEX "idx_payment_status" ON "payments" ("status");

CREATE INDEX "idx_payment_transaction" ON "payments" ("transaction_id");

CREATE INDEX "idx_payment_created" ON "payments" ("created_at");

CREATE INDEX "idx_review_product" ON "reviews" ("product_id");

CREATE INDEX "idx_review_user" ON "reviews" ("user_id");

CREATE UNIQUE INDEX "idx_review_unique" ON "reviews" ("product_id", "user_id");

CREATE INDEX "idx_review_rating" ON "reviews" ("rating");

CREATE INDEX "idx_review_helpful_count" ON "reviews" ("helpful_count");

CREATE INDEX "idx_review_created" ON "reviews" ("created_at");

CREATE UNIQUE INDEX "idx_review_helpful_unique" ON "review_helpful" ("user_id", "review_id");

CREATE INDEX "idx_review_helpful_review" ON "review_helpful" ("review_id");

COMMENT ON COLUMN "products"."price" IS 'Must be > 0';

COMMENT ON COLUMN "products"."stock_quantity" IS 'Must be >= 0';

COMMENT ON COLUMN "products"."weight_kg" IS 'Must be > 0 if provided';

COMMENT ON TABLE "carts" IS 'Business rule: Either user_id OR session_id must be NOT NULL (enforced in application)';

COMMENT ON COLUMN "carts"."user_id" IS 'NULL for guest carts';

COMMENT ON COLUMN "carts"."session_id" IS 'Required for guest carts, NULL for user carts';

COMMENT ON COLUMN "cart_items"."quantity" IS 'Must be > 0';

COMMENT ON TABLE "orders" IS 'Business rule: Either user_id OR guest_email must be NOT NULL';

COMMENT ON COLUMN "orders"."user_id" IS 'NULL for guest orders';

COMMENT ON COLUMN "orders"."guest_email" IS 'Required for guest orders';

COMMENT ON COLUMN "orders"."status" IS 'pending, pending_payment, payment_failed, pending_inventory, processing, shipped, delivered, cancelled, refunded';

COMMENT ON COLUMN "orders"."total_amount" IS 'Must be > 0';

COMMENT ON COLUMN "order_items"."quantity" IS 'Must be > 0';

COMMENT ON COLUMN "order_items"."price_at_time" IS 'Must be > 0';

COMMENT ON COLUMN "payments"."amount" IS 'Must be > 0';

COMMENT ON COLUMN "payments"."status" IS 'pending, processing, successful, failed, refunded';

COMMENT ON COLUMN "payments"."payment_method" IS 'stripe, paypal, etc';

COMMENT ON COLUMN "payments"."transaction_id" IS 'External payment provider transaction ID';

COMMENT ON TABLE "reviews" IS 'Business rule: One review per user per product';

COMMENT ON COLUMN "reviews"."rating" IS 'Must be between 1-5';

COMMENT ON COLUMN "reviews"."helpful_count" IS 'Must be >= 0';

COMMENT ON TABLE "review_helpful" IS 'Business rule: One helpful vote per user per review';

ALTER TABLE "token_blacklist" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");

ALTER TABLE "password_reset_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");

ALTER TABLE "user_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("brand_id") REFERENCES "brands" ("id");

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");

ALTER TABLE "review_helpful" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");

ALTER TABLE "review_helpful" ADD FOREIGN KEY ("review_id") REFERENCES "reviews" ("id");

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id");
