"use client";

import { useState } from "react";
import { formatDateEuropean } from "@/lib/date-utils";
import { LightbulbIcon, SparklesIcon, CheckmarkIcon } from "./icons";
import { Button } from "./Button";

interface InsightCardProps {
  title: string;
  body: string;
  priority: "HIGH" | "MEDIUM" | "LOW";
  recommendations?: string[];
  sourceModel?: string;
  cached?: boolean;
  createdAt?: string;
  onGenerate?: () => void;
}

export function InsightCard({
  title,
  body,
  priority,
  recommendations = [],
  sourceModel,
  cached,
  createdAt,
  onGenerate,
}: InsightCardProps) {
  const [expanded, setExpanded] = useState(false);

  const priorityColors = {
    HIGH: "bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-700",
    MEDIUM: "bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-700",
    LOW: "bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-300 border-green-200 dark:border-green-700",
  };

  const priorityIcons = {
    HIGH: LightbulbIcon,
    MEDIUM: SparklesIcon,
    LOW: CheckmarkIcon,
  };

  const priorityLabels = {
    HIGH: "Important",
    MEDIUM: "Moderate",
    LOW: "Good Progress",
  };

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md border border-gray-200 dark:border-gray-700 p-6 hover:shadow-lg transition-shadow">
      {/* Header */}
      <div className="flex items-start justify-between mb-4">
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-2">
            {(() => {
              const IconComponent = priorityIcons[priority];
              return <IconComponent className={`w-5 h-5 ${priority === "HIGH" ? "text-blue-600 dark:text-blue-400" : priority === "MEDIUM" ? "text-emerald-600 dark:text-emerald-400" : "text-green-600 dark:text-green-400"}`} />;
            })()}
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">{title}</h3>
            <span
              className={`px-2 py-1 text-xs font-medium rounded border ${priorityColors[priority]}`}
            >
              {priorityLabels[priority]}
            </span>
          </div>
          {sourceModel && (
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Generated by {sourceModel}
              {cached && " (cached)"}
            </p>
          )}
          {createdAt && (
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
              {formatDateEuropean(createdAt)}
            </p>
          )}
        </div>
        {onGenerate && (
          <Button
            onClick={onGenerate}
            variant="primary"
            size="sm"
          >
            Regenerate
          </Button>
        )}
      </div>

      {/* Body */}
      <p className="text-gray-700 dark:text-gray-300 mb-4 leading-relaxed">{body}</p>

      {/* Recommendations */}
      {recommendations.length > 0 && (
        <div className="mt-4">
          <button
            onClick={() => setExpanded(!expanded)}
            className="text-sm font-medium text-blue-600 dark:text-blue-400 hover:underline mb-2"
          >
            {expanded ? "Hide" : "Show"} Recommendations ({recommendations.length})
          </button>
          {expanded && (
            <ul className="list-disc list-inside space-y-2 text-gray-600 dark:text-gray-400">
              {recommendations.map((rec, index) => (
                <li key={index} className="text-sm">
                  {rec}
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}



